import { Tool } from "@/types/tool";

export const TOOLS_REGISTRY: Tool[] = [
  {
    id: "text-encoder",
    name: "Text Encoder",
    description: "Encode and decode text with multiple formats",
    tags: ["encode", "decode", "dev", "tools"],
    category: "encoder",
    path: "/tools/text-encoder",
    icon: "Code2",
  },
  {
    id: "file-format-converter",
    name: "File Format Converter",
    description: "Convert between JSON, XML, and CSV formats",
    tags: ["json", "xml", "csv", "transform"],
    category: "converter",
    path: "/tools/file-format-converter",
    icon: "ArrowLeftRight",
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Linux file permissions (octal and symbolic)",
    tags: ["linux", "permission", "chmod", "octal", "symbolic", "devops"],
    category: "calculator",
    path: "/tools/chmod-calculator",
    icon: "Lock",
  },
  {
    id: "code-formatter",
    name: "Code Formatter",
    description: "Format and beautify your code",
    tags: ["clean", "prettier", "indent", "dev"],
    category: "formatter",
    path: "/tools/code-formatter",
    icon: "Code",
  },
  {
    id: "json-explorer",
    name: "JSON Explorer",
    description: "Visualize JSON data as a tree",
    tags: ["json", "tree", "view", "parse"],
    category: "developer",
    path: "/tools/json-explorer",
    icon: "FileJson",
  },
  {
    id: "icon-generator",
    name: "Icon Generator",
    description: "Generate favicons and app icons from an image",
    tags: ["icon", "favicon", "image", "generator", "pwa"],
    category: "designer",
    path: "/tools/icon-generator",
    icon: "Image",
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove backgrounds from PNG and GIF images by color",
    tags: ["image", "transparent", "png", "gif", "background", "remove", "alpha"],
    category: "designer",
    path: "/tools/background-remover",
    icon: "Eraser",
  },
  {
    id: "ip-subnet-calculator",
    name: "IP Subnet Calculator",
    description: "Calculate IPv4/IPv6 subnet masks, ranges, and CIDR",
    tags: ["ip", "network", "subnet", "cidr", "mask", "devops"],
    category: "calculator",
    path: "/tools/ip-subnet-calculator",
    icon: "Network",
  },
  {
    id: "json-csv-converter",
    name: "JSON ↔ CSV",
    description: "Convert between JSON and CSV formats",
    tags: ["export", "import", "convert", "data"],
    category: "converter",
    path: "/tools/json-csv-converter",
    icon: "FileSpreadsheet",
  },
  {
    id: "json-to-code",
    name: "JSON to Code",
    description: "Generate Python classes or TypeScript interfaces from JSON",
    tags: ["interface", "type", "class", "model", "generator", "dev"],
    category: "generator",
    path: "/tools/json-to-code",
    icon: "FileCode",
  },
  {
    id: "json-schema-gen",
    name: "JSON Schema Gen",
    description: "Generate JSON schema from data",
    tags: ["validator", "schema", "structure"],
    category: "generator",
    path: "/tools/json-schema-gen",
    icon: "FileCheck",
  },
  {
    id: "base64-converter",
    name: "Base64 Converter",
    description: "Encode and decode Base64",
    tags: ["b64", "encoding", "security", "web"],
    category: "encoder",
    path: "/tools/base64-converter",
    icon: "Binary",
  },
  {
    id: "binary-hex-converter",
    name: "Binary ↔ HEX",
    description: "Convert between binary and hexadecimal",
    tags: ["bin", "hex", "low-level", "dev"],
    category: "converter",
    path: "/tools/binary-hex-converter",
    icon: "Binary",
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Encode and decode URLs",
    tags: ["uri", "encoding", "web", "browser"],
    category: "encoder",
    path: "/tools/url-encoder",
    icon: "Link",
  },
  {
    id: "short-url-gen",
    name: "Short URL Gen",
    description: "Generate short URLs",
    tags: ["link", "tiny", "web", "redirect"],
    category: "generator",
    path: "/tools/short-url-gen",
    icon: "Link2",
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and verify JWT tokens",
    tags: ["auth", "token", "security", "json"],
    category: "security",
    path: "/tools/jwt-decoder",
    icon: "Key",
  },
  {
    id: "html-entities",
    name: "HTML Entities",
    description: "Encode and decode HTML entities",
    tags: ["escape", "entity", "web", "html"],
    category: "encoder",
    path: "/tools/html-entities",
    icon: "Code2",
  },
  {
    id: "text-case",
    name: "Text Case",
    description: "Convert text case (upper, lower, camel, etc.)",
    tags: ["upper", "lower", "camel", "format"],
    category: "formatter",
    path: "/tools/text-case",
    icon: "Type",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate SHA256, MD5, and other hashes",
    tags: ["sha256", "md5", "security", "crypto"],
    category: "security",
    path: "/tools/hash-generator",
    icon: "Hash",
  },
  {
    id: "encryption-tool",
    name: "Encryption Tool",
    description: "Encrypt and decrypt with AES",
    tags: ["aes", "security", "crypto", "lock"],
    category: "security",
    path: "/tools/encryption-tool",
    icon: "Lock",
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate unique identifiers",
    tags: ["guid", "id", "unique", "random"],
    category: "generator",
    path: "/tools/uuid-generator",
    icon: "Fingerprint",
  },
  {
    id: "password-gen",
    name: "Password Gen",
    description: "Generate secure passwords",
    tags: ["security", "random", "auth", "key"],
    category: "generator",
    path: "/tools/password-gen",
    icon: "KeyRound",
  },
  {
    id: "timestamp-conv",
    name: "Timestamp Conv",
    description: "Convert Unix timestamps to dates",
    tags: ["unix", "time", "date", "epoch"],
    category: "converter",
    path: "/tools/timestamp-conv",
    icon: "Clock",
  },
  {
    id: "cron-expression",
    name: "Cron Expression",
    description: "Build and parse cron expressions",
    tags: ["schedule", "linux", "server", "time"],
    category: "developer",
    path: "/tools/cron-expression",
    icon: "Calendar",
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions",
    tags: ["pattern", "string", "test", "regex"],
    category: "developer",
    path: "/tools/regex-tester",
    icon: "Search",
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format SQL queries",
    tags: ["db", "query", "format", "sql"],
    category: "formatter",
    path: "/tools/sql-formatter",
    icon: "Database",
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare and diff text",
    tags: ["compare", "patch", "merge", "text"],
    category: "developer",
    path: "/tools/text-diff",
    icon: "FileText",
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Preview markdown in real-time",
    tags: ["md", "editor", "preview", "docs"],
    category: "formatter",
    path: "/tools/markdown-preview",
    icon: "FileType",
  },
  {
    id: "markup-converter",
    name: "Markup Converter",
    description: "Convert between Markdown and Atlassian Wiki Markup",
    tags: ["markdown", "jira", "confluence", "wiki", "convert"],
    category: "converter",
    path: "/tools/markup-converter",
    icon: "FileText",
  },
  {
    id: "pdf-tools",
    name: "PDF Editor/Tools",
    description: "Edit and manipulate PDF files",
    tags: ["pdf", "merge", "edit", "document"],
    category: "other",
    path: "/tools/pdf-tools",
    icon: "FileText",
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert units (weight, length, etc.)",
    tags: ["math", "weight", "length", "calc"],
    category: "calculator",
    path: "/tools/unit-converter",
    icon: "Calculator",
  },
  {
    id: "date-dday-calc",
    name: "Date/D-Day Calc",
    description: "Calculate days between dates",
    tags: ["calendar", "anniversary", "time"],
    category: "calculator",
    path: "/tools/date-dday-calc",
    icon: "CalendarDays",
  },
  {
    id: "salary-tax-calc",
    name: "Salary/Tax Calc",
    description: "Calculate salary and taxes",
    tags: ["money", "finance", "business", "tax"],
    category: "calculator",
    path: "/tools/salary-tax-calc",
    icon: "DollarSign",
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate loan payments and interest",
    tags: ["interest", "bank", "money", "finance"],
    category: "calculator",
    path: "/tools/loan-calculator",
    icon: "Banknote",
  },
  {
    id: "command-palette",
    name: "Command Palette",
    description: "Save and quickly copy frequently used commands or snippets",
    tags: ["command", "snippet", "clipboard", "productivity", "terminal"],
    category: "developer",
    path: "/tools/command-palette",
    icon: "Terminal",
  },
  {
    id: "compound-interest-calculator",
    name: "Compound Interest Calc",
    description: "Visualize compound interest growth over time",
    tags: ["money", "finance", "investment", "interest", "fire"],
    category: "calculator",
    path: "/tools/compound-interest-calculator",
    icon: "TrendingUp",
  },
  {
    id: "design-tools",
    name: "Design Tools",
    description: "Color picker, palette, and image tools",
    tags: ["color", "hex", "palette", "image", "resize"],
    category: "designer",
    path: "/tools/design-tools",
    icon: "Palette",
  },
  {
    id: "image-filters",
    name: "Image Filters",
    description: "Apply brightness, contrast, and other filters to images",
    tags: ["image", "filter", "edit", "photo", "canvas"],
    category: "designer",
    path: "/tools/image-filters",
    icon: "Image",
  },
  {
    id: "pixel-art-editor",
    name: "Pixel Art Editor",
    description: "Create pixel art icons and sprites",
    tags: ["pixel", "art", "icon", "editor", "draw", "sprite"],
    category: "designer",
    path: "/tools/pixel-art-editor",
    icon: "Grid",
  },
  {
    id: "qr-code-gen",
    name: "QR Code Gen",
    description: "Generate QR codes",
    tags: ["qr", "link", "mobile", "scan"],
    category: "generator",
    path: "/tools/qr-code-gen",
    icon: "QrCode",
  },
  {
    id: "keyword-density",
    name: "Keyword Density",
    description: "Calculate keyword density and frequency",
    tags: ["seo", "keyword", "density", "frequency", "content"],
    category: "calculator",
    path: "/tools/keyword-density",
    icon: "Search",
  },
  {
    id: "meta-tag-checker",
    name: "Meta Tag Checker",
    description: "Check meta title and description lengths",
    tags: ["seo", "meta", "title", "description", "optimization"],
    category: "calculator",
    path: "/tools/meta-tag-checker",
    icon: "Tag",
  },
  {
    id: "reading-time-calc",
    name: "Reading Time Calc",
    description: "Calculate estimated reading time",
    tags: ["seo", "content", "reading", "time", "blog"],
    category: "calculator",
    path: "/tools/reading-time-calc",
    icon: "BookOpen",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, and sentences",
    tags: ["seo", "word", "count", "character", "text"],
    category: "calculator",
    path: "/tools/word-counter",
    icon: "FileText",
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Generate SEO-friendly URL slugs",
    tags: ["seo", "url", "slug", "permalink", "optimization"],
    category: "generator",
    path: "/tools/slug-generator",
    icon: "Link",
  },
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate robots.txt file for SEO",
    tags: ["seo", "robots", "crawl", "google", "sitemap"],
    category: "generator",
    path: "/tools/robots-txt-generator",
    icon: "Bot",
  },
  {
    id: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate XML sitemap structure",
    tags: ["seo", "sitemap", "xml", "google", "crawl"],
    category: "generator",
    path: "/tools/sitemap-generator",
    icon: "Map",
  },
  {
    id: "open-graph-generator",
    name: "Open Graph Generator",
    description: "Generate Open Graph meta tags",
    tags: ["seo", "og", "facebook", "social", "meta"],
    category: "generator",
    path: "/tools/open-graph-generator",
    icon: "Share2",
  },
  {
    id: "schema-markup-generator",
    name: "Schema Markup Gen",
    description: "Generate JSON-LD schema markup",
    tags: ["seo", "schema", "structured-data", "json-ld", "rich-snippets"],
    category: "generator",
    path: "/tools/schema-markup-generator",
    icon: "Code2",
  },
  {
    id: "canonical-url-checker",
    name: "Canonical URL Checker",
    description: "Validate and generate canonical URLs",
    tags: ["seo", "canonical", "url", "duplicate", "content"],
    category: "calculator",
    path: "/tools/canonical-url-checker",
    icon: "Link2",
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Focus timer with work and break intervals",
    tags: ["timer", "focus", "productivity", "pomodoro", "time"],
    category: "other",
    path: "/tools/pomodoro-timer",
    icon: "Timer",
  },
  {
    id: "encoding-converter",
    name: "Encoding Converter",
    description: "Fix broken text (mojibake) by converting between character encodings",
    tags: ["encoding", "utf8", "charset", "mojibake", "unicode", "text", "language"],
    category: "converter",
    path: "/tools/encoding-converter",
    icon: "Languages",
  },
  {
    id: "ai-chat",
    name: "AI Chat",
    description: "Chat with your local Ollama LLM",
    tags: ["ai", "chat", "llm", "ollama"],
    category: "ai",
    path: "/tools/ai-chat",
    icon: "MessageSquare",
  },
];
